###
GET http://localhost:3000/api/credentials

###
POST http://localhost:3000/api/credentials
Content-Type: application/json

{
    "email": "dennysss51saaas585555p@unl.edu.ec",
    "password": "12345",
    "user": "5e0ffaad-3d88-4da7-8abe-4906c8545321"
}

###
PUT http://localhost:3000/api/credentials/5b486820-ce9d-4961-9b3f-f78f2eee54b7
Content-Type: application/json

{
    "email": "correoactalizado@unl.edu.ec",
    "lastpassword": "12345",
    "password": "12345"
}

###
GET http://localhost:3000/api/credentials/5b486820-ce9d-4961-9b3f-f78f2eee54b7

###
DELETE  http://localhost:3000/api/credentials/5b486820-ce9d-4961-9b3f-f78f2eee54b7
