###
GET http://localhost:3000/api/credentials

###
POST http://localhost:3000/api/credentials
Content-Type: application/json

{
    "email": "dennyss2p@unl.edu.ec",
    "password": "12345",
    "user": "30840a0d-37ed-4e92-b3f0-f9a9b1e979c3"
}

###
PUT http://localhost:3000/api/credentials/d502a9e8-98c9-487b-8ebd-0e0b09f5c567
Content-Type: application/json

{
    "email": "dennysactualizado@unl.edu.ec",
    "lastpassword": "12348",
    "password": "12349"
}

###
GET http://localhost:3000/api/credentials/d502a9e8-98c9-487b-8ebd-0e0b09f5c567

###
DELETE  http://localhost:3000/api/credentials/d502a9e8-98c9-487b-8ebd-0e0b09f5c567
