###
GET http://localhost:3000/api/users
###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "juanito new",
    "lastname": "perez",
    "phone": "0982763941"
}

###
GET http://localhost:3000/api/users/6691f08d-6e29-4026-86af-2e1d9c61fbce

###
PUT http://localhost:3000/api/users/6691f08d-6e29-4026-86af-2e1d9c61fbce
Content-Type: application/json

{
    "name": "juan ultra modificado",
    "lastname": "perez",
    "phone": "0982763941"
}

###
DELETE http://localhost:3000/api/users/6691f08d-6e29-4026-86af-2e1d9c61fbce